export type {
  HeaderNavChildItem,
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  FrontmatterPreviewConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  TagVocabularyEntry,
  MetaTagsConfig,
} from "./settings-types";
import type {
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  FrontmatterPreviewConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  MetaTagsConfig,
} from "./settings-types";

export const settings = {
  colorScheme: "Default Dark",
  colorMode: {
    defaultMode: "dark",
    lightScheme: "Default Light",
    darkScheme: "Default Dark",
    respectPrefersColorScheme: true,
  } satisfies ColorModeConfig as ColorModeConfig | false,
  siteName: "zudo-codemirror-wisdom",
  siteDescription: "Takazudo's CodeMirror 6 dev notes for me and AI agents" as string,
  base: "/",
  trailingSlash: false as boolean,
  noindex: false as boolean,
  editUrl: false as string | false,
  githubUrl: "https://github.com/Takazudo/zudo-codemirror-wisdom" as string | false,
  siteUrl: "https://zudo-codemirror-wisdom.takazudomodular.com" as string,
  metaTags: {
    description: true,
    keywords: "",
    ogImage: "/img/ogp.png",
    ogSiteName: true,
    twitterCard: "summary_large_image",
    twitterCreator: "@Takazudo",
  } satisfies MetaTagsConfig as MetaTagsConfig,
  docsDir: "src/content/docs",
  defaultLocale: "en" as const,
  locales: {
    ja: { label: "JA", dir: "src/content/docs-ja" },
  } satisfies Record<string, LocaleConfig>,
  mermaid: true,
  sitemap: false,
  docMetainfo: false,
  docTags: false,
  tagPlacement: "after-title" as TagPlacement,
  tagGovernance: "off" as TagGovernanceMode,
  tagVocabulary: false as boolean,
  frontmatterPreview: false as FrontmatterPreviewConfig | false,
  llmsTxt: true,
  math: false,
  cjkFriendly: true as boolean,
  onBrokenMarkdownLinks: "warn" as "warn" | "error" | "ignore",
  aiAssistant: false as boolean,
  aiChatDemoMode: false as boolean,
  aiChatAllowedOrigins: [] as string[],
  aiChatGlobalDailyLimit: false as number | false,
  docHistory: true,
  bodyFootUtilArea: {
    docHistory: true,
    viewSourceLink: false,
  } satisfies BodyFootUtilAreaConfig as BodyFootUtilAreaConfig | false,
  designTokenPanel: false as boolean,
  tocMinDepth: 2 as number,
  tocMaxDepth: 4 as number,
  headingIdStrategy: "hierarchical" as "flat" | "hierarchical",
  sidebarResizer: true as boolean,
  sidebarToggle: true as boolean,
  imageEnlarge: true as boolean,
  // CM6 IIFE bundle injected into every HtmlPreview iframe head so live demos
  // can reach `window.CM.*`. The wrapper does NOT base-prefix this raw string,
  // and base is "/" here, so the absolute /assets/... path resolves directly.
  htmlPreview: {
    head: '<script src="/assets/cm6-bundle.min.js"></script>',
  } as HtmlPreviewConfig | undefined,
  versions: false as VersionConfig[] | false,
  claudeResources: {
    claudeDir: ".claude",
  } as { claudeDir: string; projectRoot?: string } | false,
  defaultLocaleOnlyPrefixes: [
    "/docs/claude/",
    "/docs/claude-md/",
    "/docs/claude-skills/",
  ] as string[],
  footer: {
    links: [],
    copyright: `Copyright © ${new Date().getFullYear()} <a href="https://x.com/Takazudo" rel="nofollow noreferrer noopener" target="_blank">Takazudo</a>. Built with <a href="https://zudo-doc.takazudomodular.com/" rel="nofollow noreferrer noopener" target="_blank">zudo-doc</a>. Enjoy synth on <a href="https://takazudomodular.com/" rel="nofollow noreferrer noopener" target="_blank">Takazudo Modular</a>.`,
  } satisfies FooterConfig as FooterConfig | false,
  headerNav: [
    { label: "Overview", path: "/docs/overview", categoryMatch: "overview" },
    { label: "Core", path: "/docs/core", categoryMatch: "core" },
    { label: "Vim Mode", path: "/docs/vim-mode", categoryMatch: "vim-mode" },
    { label: "Extensions", path: "/docs/extensions", categoryMatch: "extensions" },
    { label: "Recipes", path: "/docs/recipes", categoryMatch: "recipes" },
    { label: "Claude", path: "/docs/claude", categoryMatch: "claude" },
  ] satisfies HeaderNavItem[] as HeaderNavItem[],
  headerRightItems: [
    { type: "component", component: "github-link" },
    { type: "component", component: "theme-toggle" },
    { type: "component", component: "search" },
    { type: "component", component: "language-switcher" },
  ] satisfies HeaderRightItem[] as HeaderRightItem[],
  // Enable the package-owned route-injection plugin (@takazudo/zudo-doc/plugins/routes):
  // the 1.x package supplies the docs / 404 / sitemap / robots / tags / versions routes
  // at build time, so the host no longer ships those page stubs. zudoDocPreset() does NO
  // defaulting — omitting this field is treated as off (routes would not be injected).
  packageOwnedRoutes: true,
};
